name: CI/CD Pipeline - LKS Cloud Computing

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
  ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
  EB_APPLICATION_NAME: ${{ secrets.EB_APP_NAME }}
  EB_ENVIRONMENT_NAME: ${{ secrets.EB_ENV_NAME }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # =========================
    # STEP 1 — Checkout Repo
    # =========================
    - name: Checkout code
      uses: actions/checkout@v4

    # =========================
    # STEP 2 — AWS Credentials
    # =========================
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    # =========================
    # STEP 3 — Login ECR
    # =========================
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # =========================
    # STEP 4 — Build Docker Image
    # =========================
    - name: Build Docker image
      run: |
        docker build -t $ECR_REPOSITORY:latest .

    # =========================
    # STEP 5 — Tag Image
    # =========================
    - name: Tag Docker image
      run: |
        docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest

    # =========================
    # STEP 6 — Push Image
    # =========================
    - name: Push Docker image to ECR
      run: |
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    # =========================
    # STEP 7 — Dockerrun
    # =========================
    - name: Generate Dockerrun.aws.json
      run: |
        cat <<EOF > Dockerrun.aws.json
        {
          "AWSEBDockerrunVersion": 1,
          "Image": {
            "Name": "$ECR_REGISTRY/$ECR_REPOSITORY:latest",
            "Update": "true"
          },
          "Ports": [
            {
              "ContainerPort": "5000"
            }
          ]
        }
        EOF

    # =========================
    # STEP 8 — ZIP
    # =========================
    - name: Zip deploy package
      run: zip deploy.zip Dockerrun.aws.json

    # =========================
    # STEP 9 — Deploy EB
    # =========================
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ env.EB_APPLICATION_NAME }}
        environment_name: ${{ env.EB_ENVIRONMENT_NAME }}
        region: ${{ env.AWS_REGION }}
        version_label: "v-${{ github.run_number }}"
        deployment_package: deploy.zip
